/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#3b0900',
        'secondary-fixed': '#b8f1b1',
        'secondary-fixed-dim': '#9dd496',
        'on-primary-fixed': '#161e00',
        'outline-variant': '#c5c9b1',
        'on-tertiary-container': '#6b1800',
        error: '#ba1a1a',
        outline: '#757964',
        'on-secondary': '#ffffff',
        'on-surface': '#1b1d0e',
        'tertiary-fixed': '#ffdbd1',
        'on-secondary-fixed-variant': '#1f5121',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-dim': '#dbdbc4',
        background: '#fbfbe3',
        'on-secondary-fixed': '#002204',
        'surface-variant': '#e4e4cc',
        'tertiary-fixed-dim': '#ffb5a0',
        'surface-container-low': '#f5f5dd',
        'primary-fixed-dim': '#b1d43d',
        'surface-container': '#efefd7',
        'on-tertiary-fixed-variant': '#872000',
        'primary-container': '#8bac0f',
        surface: '#fbfbe3',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#3c4d00',
        'on-secondary-container': '#3b6e3a',
        primary: '#516600',
        'primary-fixed': '#ccf157',
        'surface-container-highest': '#e4e4cc',
        'on-error-container': '#93000a',
        'surface-container-high': '#eaead2',
        'secondary-container': '#b5eeae',
        'on-primary-container': '#2e3c00',
        'surface-tint': '#516600',
        'inverse-primary': '#b1d43d',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#f2f2da',
        secondary: '#376936',
        'inverse-surface': '#303222',
        'on-background': '#1b1d0e',
        'surface-bright': '#fbfbe3',
        'tertiary-container': '#ff7751',
        tertiary: '#b12d00',
        'on-surface-variant': '#454936',
      },
      spacing: {
        gutter: '16px',
        'margin-md': '32px',
        'margin-lg': '64px',
        'margin-sm': '16px',
        unit: '8px',
      },
      fontFamily: {
        'label-caps': ['DotGothic16', 'sans-serif'],
        'headline-lg': ['DotGothic16', 'sans-serif'],
        'headline-lg-mobile': ['DotGothic16', 'sans-serif'],
        'body-lg': ['DotGothic16', 'sans-serif'],
        'body-sm': ['DotGothic16', 'sans-serif'],
        'headline-md': ['DotGothic16', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['10px', { lineHeight: '12px', fontWeight: '700' }],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '2px', fontWeight: '700' },
        ],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-md': [
          '24px',
          { lineHeight: '32px', letterSpacing: '1px', fontWeight: '700' },
        ],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
